### ISSUE TITLE
I would like to execute this using Java 8.

### ISSUE THREAD

**Issue by xiaochunkun** [vectrix-space/ignite#120] opened 2023-01-22 08:43 UTC
[cpw.mods.modlauncher.LaunchServiceHandler]: Launching target 'ignitelaunch' with arguments [ignite.paper.override=false, paper.jar]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at space.vectrix.ignite.applaunch.IgniteBootstrap.run(IgniteBootstrap.java:192)
        at space.vectrix.ignite.applaunch.IgniteBootstrap.main(IgniteBootstrap.java:99)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.launchService0(IgniteLaunchService.java:214)
        at space.vectrix.ignite.applaunch.handler.IgniteLaunchService.lambda$launchService$1(IgniteLaunchService.java:112)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 6 more
Caused by: java.lang.NullPointerException
        at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
        at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
        at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:65)
        at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedTypes(TypeAnnotationParser.java:137)
        at java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:695)
        at com.google.inject.spi.InjectionPoint.<init>(InjectionPoint.java:101)
        at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:326)
        at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:121)
        at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:715)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:223)
        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949)
        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at space.vectrix.ignite.launch.IgniteLaunch.<init>(IgniteLaunch.java:53)
        at space.vectrix.ignite.launch.IgniteLaunch.main(IgniteLaunch.java:46)
        ... 13 more

**Comment by Cecer** [comment] 2023-02-08 18:02
I've done a little digging and it appears that this is caused by [JDA-8152174](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8152174).

While not really a solution, I was able to work around this issue with a custom build where I removed the NonNull annotations from the constructor parameters of `space.vectrix.ignite.launch.IgnitePlatform`.

```
  @Inject
  public IgnitePlatform(final /*@NonNull*/ @ConfigPath(shared = true) Path configs,
                        final /*@NonNull*/ @ModsPath Path mods) {
```

**Comment by connorhartley** [comment] 2023-02-18 00:49
Fixed in https://github.com/vectrix-space/ignite/commit/63d5506386558f5c3639cf533ffd5b091bd0f79a you can download the latest version here https://github.com/vectrix-space/ignite/releases/tag/v0.8.1 .

**Closed by connorhartley** 2023-02-18 00:49 UTC
